apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: exchange-admin
  name: exchange-admin
spec:
  replicas: 3
  selector:
    matchLabels:
      app: exchange-admin
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: exchange-admin
    spec:
      containers:
      - image: asia.gcr.io/mycoin-331119/exchange-admin
        imagePullPolicy: Always
        name: exchange-admin